export const POKEMON_CLASSES = {
  normal: {
    bg: 'bg-gray-50',
    border: 'border-gray-200',
    badge: 'bg-gray-500',
    icon: '⚪',
    gradient: 'from-gray-300 to-gray-500',
    text: 'text-gray-700',
  },
  fire: {
    bg: 'bg-red-50',
    border: 'border-red-200',
    badge: 'bg-orange-500',
    icon: '🔥',
    gradient: 'from-orange-400 to-red-600',
    text: 'text-red-700',
  },
  water: {
    bg: 'bg-blue-50',
    border: 'border-blue-200',
    badge: 'bg-blue-500',
    icon: '💧',
    gradient: 'from-blue-400 to-cyan-600',
    text: 'text-blue-700',
  },
  electric: {
    bg: 'bg-yellow-50',
    border: 'border-yellow-200',
    badge: 'bg-yellow-500',
    icon: '⚡',
    gradient: 'from-yellow-300 to-yellow-500',
    text: 'text-yellow-700',
  },
  grass: {
    bg: 'bg-green-50',
    border: 'border-green-200',
    badge: 'bg-green-500',
    icon: '🌿',
    gradient: 'from-green-400 to-emerald-600',
    text: 'text-green-700',
  },
  ice: {
    bg: 'bg-blue-50',
    border: 'border-blue-100',
    badge: 'bg-blue-300',
    icon: '❄️',
    gradient: 'from-blue-200 to-blue-400',
    text: 'text-blue-600',
  },
  fighting: {
    bg: 'bg-red-50',
    border: 'border-red-300',
    badge: 'bg-red-700',
    icon: '👊',
    gradient: 'from-red-600 to-red-800',
    text: 'text-red-800',
  },
  poison: {
    bg: 'bg-purple-50',
    border: 'border-purple-200',
    badge: 'bg-purple-500',
    icon: '☠️',
    gradient: 'from-purple-400 to-purple-600',
    text: 'text-purple-700',
  },
  ground: {
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    badge: 'bg-amber-600',
    icon: '🌍',
    gradient: 'from-yellow-600 to-amber-800',
    text: 'text-amber-700',
  },
  flying: {
    bg: 'bg-indigo-50',
    border: 'border-indigo-200',
    badge: 'bg-indigo-400',
    icon: '🦅',
    gradient: 'from-indigo-300 to-blue-400',
    text: 'text-indigo-700',
  },
  psychic: {
    bg: 'bg-pink-50',
    border: 'border-pink-200',
    badge: 'bg-pink-500',
    icon: '🔮',
    gradient: 'from-pink-400 to-purple-500',
    text: 'text-pink-700',
  },
  bug: {
    bg: 'bg-lime-50',
    border: 'border-lime-200',
    badge: 'bg-lime-500',
    icon: '🐛',
    gradient: 'from-lime-400 to-green-600',
    text: 'text-lime-700',
  },
  rock: {
    bg: 'bg-stone-50',
    border: 'border-stone-200',
    badge: 'bg-stone-500',
    icon: '🪨',
    gradient: 'from-stone-400 to-stone-600',
    text: 'text-stone-700',
  },
  ghost: {
    bg: 'bg-indigo-50',
    border: 'border-indigo-300',
    badge: 'bg-indigo-700',
    icon: '👻',
    gradient: 'from-indigo-600 to-purple-800',
    text: 'text-indigo-800',
  },
  dragon: {
    bg: 'bg-purple-50',
    border: 'border-purple-300',
    badge: 'bg-purple-600',
    icon: '🐉',
    gradient: 'from-purple-500 to-indigo-700',
    text: 'text-purple-700',
  },
  dark: {
    bg: 'bg-gray-100',
    border: 'border-gray-400',
    badge: 'bg-gray-800',
    icon: '🌑',
    gradient: 'from-gray-700 to-black',
    text: 'text-gray-800',
  },
  steel: {
    bg: 'bg-slate-50',
    border: 'border-slate-200',
    badge: 'bg-slate-500',
    icon: '⚙️',
    gradient: 'from-slate-400 to-slate-600',
    text: 'text-slate-700',
  },
  fairy: {
    bg: 'bg-pink-50',
    border: 'border-pink-200',
    badge: 'bg-rose-400',
    icon: '🧚',
    gradient: 'from-pink-300 to-rose-500',
    text: 'text-pink-700',
  },
  // Default if type not found or loading
  default: {
    bg: 'bg-gray-50',
    border: 'border-gray-200',
    badge: 'bg-gray-400',
    icon: '❓',
    gradient: 'from-gray-200 to-gray-400',
    text: 'text-gray-600',
  },
};
